dataset: ../data/250k_rndm_zinc_drugs_clean.smi
output_model_dir: ../model/user_trained
output_token: ../model/user_trained/tokens.pkl

dropout_rate: 0.3
rec_dropout_rate: 0
learning_rate: 0.001
epoch: 100
batch_size: 512
validation_split: 0.1
units: 256
maxlen: 82
