dataloader:
    infile: ./ABL.csv
    target: smiles
    tasks: ["value"]
    featurizer:
        type: ConvMolFeaturizer
        kwargs:
            per_atom_fragmentation: False
    transformers: ['NormalizationTransformer']
    
splitter:
    type: RandomStratifiedSplitter
    kwargs: 
    method: train_test_split
    rate: { 'train': 0.8, 'valid': 0.2, 'test': 0.2, 'k': 5 }

training:
    n_tasks: 1
    graph_conv_layers: [64, 64]
    dense_layer_size: 64
    dropout: 0.5
    mode: 'regression'
    number_atom_features: 75
    n_classes: None
    batch_size: 100
    batch_normalize: True
    uncertainty: True
    model_dir: './model_train'
    nb_epoch: 100
    metrics: ["r2_score","pearson_r2_score","mean_squared_error","mean_absolute_error","rms_score","mae_score"]
    valid_metric: "pearson_r2_score"
    valid_interval: 2
    
#hyperopt:
#    params:
#        graph_conv_layers: [[64, 64],[64, 64, 64]]
#        dense_layer_size: [64, 128, 256]
#        dropout: { 'low': 0.2, 'high': 0.5 }
#        learning_rate: { 'high': 0.001, 'low': 0.0001}
#    algo: "tpe"
#    max_evals: 3
#    timeout: 3600
    
    
