# Basic setting
c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: generation_num
#hours: 0.01
generation_num: 300
output_dir: result/vina-gpu_geodiff
model_setting:
  model_json: model/model_chembl220k.tf25.json
  model_weight: model/model_chembl220k.tf25.best.ckpt.h5
token: model/tokens_chembl220k.pkl
reward_setting:
  reward_module: reward.VinaGPU_binary_geodiff_reward
  reward_class: VinaGPU_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: False
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: True
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

# User setting for Geodiff
geodiff_ckpt_path: /home/stsuser2/shitamichi/work2023/GeoDiff/logs/drugs_default/checkpoints/drugs_default.pt
geodiff_tag: geodiff
geodiff_clip: 1000.0
geodiff_n_steps: 5000
geodiff_global_start_sigma: 0.5
geodiff_w_global: 1.0
geodiff_sampling_type: ld
geodiff_eta: 1.0
geodiff_edge_order: 3
geodiff_save_data: True
geodiff_log_dir: ./result/vina-gpu_geodiff/geodiff
geodiff_seed: 12345


# User setteing for Vina-GPU
vina_bin_path: /home/stsuser2/shitamichi/work2023/Vina-GPU-2.0/Vina-GPU+/Vina-GPU
boost_lib_path: /home/stsuser2/shitamichi/work2023/boost_1_82_0/stage/lib
vina_receptor: ./data/1iep_receptor.pdbqt
#vina_flex: ""
vina_thread: 8000
#vina_search_depth: 1
vina_center: [15.190, 53.903, 16.917]
vina_box_size: [20, 20, 20]
vina_num_modes: 10
vina_energy_range: 3
#vina_gpus: 1
vina_base_score: -20
