# Basic setting
c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: generation_num
#hours: 0.01
generation_num: 300
output_dir: result/example_linker
model_setting:
  model_json: model/model_linker.tf25.json
  model_weight: model/model_linker.tf25.best.ckpt.h5
token: model/tokens_linker.pkl
reward_setting: 
  reward_module: reward.Linker_logP_reward
  reward_class: Linker_LogP_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
use_attachment_points_filter: False
attachment_points_filter:
  module: filter.attachment_points_filter
  class: AttachmentPointsFilter
  threshold: 2
include_filter_result_in_reward: False

# Settings for linker generation
cores: ['C1([*:1])C=CC(O)=CC=1', 'C1(=CC=NC=C1)[*:2]']