# Basic setting
c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: generation_num
#hours: 0.01
generation_num: 3
output_dir: result/diffdock-2
model_setting:
  model_json: model/model_chembl220k.tf25.json
  model_weight: model/model_chembl220k.tf25.best.ckpt.h5
token: model/tokens_chembl220k.pkl
reward_setting:
  reward_module: reward.DiffDock_Vina_reward
  reward_class: DiffDock_Vina_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 3
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: False
restart: False
checkpoint_file: chemtsv2.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: False
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: True
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False

# User setting
conda_cmd: /home/stsuser2/shitamichi/miniconda3/bin/conda
diffdock_conda_env: diffdock
diffdock_pythonpath: /home/stsuser2/shitamichi/work2023/DiffDock
diffdock_complex_name: 1iep
diffdock_protein_path: data/1iep_receptor.pdb
diffdock_protein_sequence: null
diffdock_out_dir: ./result/diffdock-2
diffdock_samples_per_complex: 10
diffdock_model_dir: ~/shitamichi/work2023/DiffDock/workdir/paper_score_model
diffdock_ckpt: best_ema_inference_epoch_model.pt
diffdock_confidence_model_dir: ~/shitamichi/work2023/DiffDock/workdir/paper_confidence_model
diffdock_confidence_ckpt: best_model_epoch75.pt
diffdock_batch_size: 32
diffdock_no_final_step_noise: False
diffdock_inference_steps: 20
diffdock_actual_steps: 18

vina_sf_name: vina
vina_cpus: 8
vina_receptor: data/1iep_receptor.pdbqt
vina_center: [15.190, 53.903, 16.917]
vina_box_size: [20, 20, 20]
vina_spacing: 0.375
vina_exhaustiveness: 32
vina_n_poses: 10
vina_base_score: -20
vina_min_rmsd: 1.0
vina_max_evals: 0
